### ISSUE TITLE
Waiting for ZeroTier system services...

### ISSUE THREAD

**Issue by cdlinsen** [zerotier/DesktopUI#19]
Windows server 2022 

![image](https://user-images.githubusercontent.com/9855816/146662782-be811000-ea2a-4a69-9418-cebea3fab74c.png)

![image](https://user-images.githubusercontent.com/9855816/146662821-6b582d5c-f8b5-4fa7-9dc5-487b777a0c43.png)

**Comment by dec0dOS** [comment]
The same error persists on Apple Silicon Mac with macOS 12.1.

**Comment by Supermilkycow** [comment]
1.8.3 the same error on Intel Mac with macOS 11.1.

**Comment by rexzhang** [comment]
1.8.5 the same error on Intel Mac with macOS 12.2.1

**Comment by adamierymenko** [comment]
This is fixed in 1.8.6, which is going out in the next hour or two. If you want the Mac version it is already up here:

http://download.zerotier.com/RELEASES/1.8.6/dist/

**Comment by adamierymenko** [comment]
1.8.6 is out now, so closing.

**Comment by dec0dOS** [comment]
The problem persists even on 1.8.6.
![Screenshot 2022-03-11 at 16 06 00](https://user-images.githubusercontent.com/14824142/157872080-d1ba02f9-92f3-4f4d-867f-335ea4eb4fd8.png)

**Comment by dec0dOS** [comment]
The problem persists even on 1.8.6.
![Screenshot 2022-03-11 at 16 10 10](https://user-images.githubusercontent.com/14824142/157872655-68052863-bf51-4f08-b1bc-0287aa89b675.png)

**Comment by adamierymenko** [comment]
Can you try quitting the UI and re-launching it? It's possible that the 1.8.6 upgrade package scripts did not do this. They should restart the UI but maybe something went wrong there. (The UI is a separate thing from the service.)

**Comment by rexzhang** [comment]
it's working after I uninstall and reinstall it.

zerotier-one 1.8.6, macOS 12.2.1

**Comment by dec0dOS** [comment]
> The problem persists even on 1.8.6.
> ![Screenshot 2022-03-11 at 16 10 10](https://user-images.githubusercontent.com/14824142/157872655-68052863-bf51-4f08-b1bc-0287aa89b675.png)

Full restart via provided scripts (`/Library/Application Support/ZeroTier/One/launch.sh`), full reinstall (`/Library/Application Support/ZeroTier/One/uninstall.sh`) does not help.

**Comment by stefandesu** [comment]
I found a thread of someone recommending to first install [1.6.6](https://download.zerotier.com/RELEASES/1.6.6/dist/), set it up, then upgrade to 1.8.6. That finally worked for me.

**Comment by CaesarYP** [comment]
> Windows server 2022
> 
> ![image](https://user-images.githubusercontent.com/9855816/146662782-be811000-ea2a-4a69-9418-cebea3fab74c.png)
> 
> ![image](https://user-images.githubusercontent.com/9855816/146662821-6b582d5c-f8b5-4fa7-9dc5-487b777a0c43.png)

请问解决了吗，我这边尝试了1.8.6、1.8.1、1.6.6，都无法使zerotier one服务启动，即便关闭防火墙并手动启动服务，这个服务也会在一秒后自动停止……但不知道为什么蒲公英组网不存在这种问题

**Comment by louis-zhou** [comment]
> 
"/Library/Application Support/ZeroTier/One"

I tried deleting the folder and reinstalling just fine.

macOS 12.1

**Comment by FLIER001** [comment]
tried all, the problem remains. zerotier 1.10, macOS 13.2 apple silicon

**Comment by FloatingLizard** [comment]
![Image](https://github.com/user-attachments/assets/15eaacd5-e9a5-4e45-ad37-9d4adb941f59)

1.14.2 TUNNELED
